Repository silverstripe/silverstripe-mfa, pull requests merged in 2019-06, with the labels that each got.

#155 FIX Support React 15 by enforcing an HTML element is returned from render
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/Register/Title.js
Labels: affects/v4, change/patch

#128 NEW Adding reset and remove buttons to managing MFA methods
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/lang/src/en.json
  client/src/boot/cms/registerReducers.js
  client/src/bundles/bundle-cms.scss
  client/src/components/FormField/RegisteredMFAMethodListField/AccountResetUI.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Remove.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Reset.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.scss
  client/src/components/FormField/RegisteredMFAMethodListField/tests/AccountResetUI-test.js
  client/src/components/FormField/RegisteredMFAMethodListField/tests/RegisteredMFAMethodListField-test.js
  client/src/components/Register.js
  client/src/components/Register/Complete.js
  client/src/components/RegisterModal.js
  client/src/components/tests/Register-test.js
  client/src/components/tests/__mocks__/lib/confirm.js
  client/src/legacy/RegisteredMFAMethodListFieldEntwine.js
  client/src/state/mfaAdministration/actionTypes.js
  client/src/state/mfaAdministration/actions.js
  client/src/state/mfaAdministration/reducer.js
  client/src/state/mfaAdministration/tests/reducer-test.js
  composer.json
  package.json
  src/Controller/AdminRegistrationController.php
  src/FormField/RegisteredMFAMethodListField.php
  src/RequestHandler/RegistrationHandlerTrait.php
  src/Service/MethodRegistry.php
  src/Service/Notification.php
  src/Service/SchemaGenerator.php
  tests/php/Controller/AdminRegistrationControllerTest.php
  yarn.lock
Labels: affects/v4, change/minor

#156 NEW Enforce sudo mode on posted MFA actions
  composer.json
  src/Authenticator/LoginHandler.php
  src/Controller/AdminRegistrationController.php
  src/RequestHandler/BaseHandlerTrait.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Authenticator/RegisterHandlerTest.php
  tests/php/Controller/AdminRegistrationControllerTest.php
Labels: affects/v4, change/minor

#162 FIX MFA notifications can now be disabled via configuration
  src/Service/Notification.php
  tests/php/Service/NotificationTest.php
Labels: affects/v4, change/patch

#161 FIX Various minor bugs:
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Register.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Reset.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/RegisterModal.js
  client/src/containers/Login.js
  client/src/state/mfaAdministration/reducer.js
Labels: affects/v4, change/patch

#166 FIX Adding CSRF to registration and verification flows
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/Register.js
  client/src/components/Verify.js
  client/src/components/tests/Register-test.js
  client/src/components/tests/Verify-test.js
  src/Authenticator/LoginHandler.php
  src/RequestHandler/RegistrationHandlerTrait.php
  src/RequestHandler/VerificationHandlerTrait.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Authenticator/RegisterHandlerTest.php
Labels: affects/v4, change/patch

#167 Bump minimum core requirement to SilverStripe 4.1
  .travis.yml
  composer.json
  readme.md
Labels: affects/v4, change/patch

#169 NEW If only one method is available during registration, automatically select it
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/Register.js
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/tests/SelectMethod-test.js
Labels: affects/v4, change/minor

#168 FIX Update default heading title selector to cater for login-forms template
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/styles/mfa.scss
Labels: affects/v4, change/patch

#170 FIX Remove admin module fonts import, removing unneeded dist files
  client/dist/fonts/silverstripe.eot
  client/dist/fonts/silverstripe.svg
  client/dist/fonts/silverstripe.ttf
  client/dist/fonts/silverstripe.woff
  client/dist/styles/bundle.css
  client/src/bundles/bundle.scss
Labels: affects/v4, change/patch

#186 API MFA is always on, and cannot be disabled
  client/dist/js/bundle-cms.js
  client/dist/styles/bundle-cms.css
  client/src/bundles/bundle-cms.scss
  client/src/legacy/SiteConfig.js
  client/src/legacy/SiteConfig.scss
  src/Extension/SiteConfigExtension.php
  src/Service/EnforcementManager.php
  tests/php/Authenticator/ChangePasswordHandlerTest.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Service/EnforcementManagerTest.php
Labels: affects/v4, change/major

#188 FIX Format backup codes consistently on download
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Register.js
  package.json
  tests/js/bootstrap.js
Labels: affects/v4, change/patch

#189 FIX ability to log in without MFA verification
  src/Service/EnforcementManager.php
  tests/php/Service/EnforcementManagerTest.php
  tests/php/Service/EnforcementManagerTest.yml
Labels: affects/v4, change/patch

#191 FIX Allow any logged in user to access the AdminRegistrationController, it implements its own checks
  src/Controller/AdminRegistrationController.php
  tests/php/Controller/AdminRegistrationControllerTest.php
Labels: affects/v4, change/patch

#195 FIX Apply MFA requirements to all LeftAndMain controllers to avoid missing Requirements from PJAX requests
  _config/admin.yml
Labels: affects/v4, change/patch

#190 NEW Method selection is now aware of "availability overrides" via Redux reducers
  .travis.yml
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/cms/registerReducers.js
  client/src/boot/index.js
  client/src/boot/registerReducers.js
  client/src/components/Icons/CircleWarning.js
  client/src/components/Register/MethodTile.js
  client/src/components/Register/tests/MethodTile-test.js
  client/src/components/Register/tests/SelectMethod-test.js
  client/src/components/Verify.js
  client/src/components/Verify.scss
  client/src/components/Verify/SelectMethod.js
  client/src/components/Verify/tests/SelectMethod-test.js
  client/src/components/tests/Verify-test.js
  client/src/containers/Login.js
  client/src/state/methodAvailability/tests/withMethodAvailability-test.js
  client/src/state/methodAvailability/withMethodAvailability.js
  client/src/state/mfaVerify/actionTypes.js
  client/src/state/mfaVerify/actions.js
  client/src/state/mfaVerify/reducer.js
  client/src/state/mfaVerify/tests/reducer-test.js
  docs/en/react-components.md
  src/RequestHandler/BaseHandlerTrait.php
  src/Service/SchemaGenerator.php
  src/State/RegisteredMethodDetails.php
  tests/php/Service/SchemaGeneratorTest.php
  yarn.lock
Labels: affects/v4, change/minor

#194 API Remove BackupCodeGeneratorInterface::hash() and allow generate() to handle its hashing internally
  docs/en/backup-codes.md
  src/BackupCode/RegisterHandler.php
  src/BackupCode/VerifyHandler.php
  src/Exception/HashFailedException.php
  src/Service/BackupCodeGenerator.php
  src/Service/BackupCodeGeneratorInterface.php
  src/State/BackupCode.php
  tests/php/BackupCode/VerifyHandlerTest.php
  tests/php/BackupCode/VerifyHandlerTest.yml
  tests/php/Service/BackupCodeGeneratorTest.php
  tests/php/Service/BackupCodeGeneratorTest/MockHashExtension.php
Labels: affects/v4, change/major

#196 FIX Remove left margin on action items in MFA screens. They have right margins from admin now.
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/containers/Login.scss
  client/src/styles/mfa-variables.scss
Labels: affects/v4, change/patch

#197 NEW Only redirect to MFA when the current member has access to part of the admin area
  src/Service/EnforcementManager.php
  tests/php/Authenticator/LoginHandlerTest.yml
  tests/php/Service/EnforcementManagerTest.php
  tests/php/Service/EnforcementManagerTest.yml
Labels: affects/v4, change/minor

#199 NEW Implement designs for unsupported options in the list of methods during MFA verification
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Verify/SelectMethod.js
  client/src/components/Verify/SelectMethod.scss
Labels: affects/v4, change/minor

#200 FIX Selected methods are correctly cleared when going back from a method to select another, or back to the introduction screen and then back to select another
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/Register.js
  client/src/components/Register/Introduction.js
  client/src/components/tests/Register-test.js
Labels: affects/v4, change/patch

#193 NEW Add ability to disable MFA via YAML configuration, restructure documentation and add example to "local-development.md"
  docs/en/datastores.md
  docs/en/debugging.md
  docs/en/encryption.md
  docs/en/local-development.md
  readme.md
  src/Service/EnforcementManager.php
  tests/php/Service/EnforcementManagerTest.php
Labels: affects/v4, change/minor, type/docs

#209 FIX Automatically selected single method now depends on the method being usable
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/tests/SelectMethod-test.js
  src/Service/MethodRegistry.php
Labels: affects/v4, change/patch

#208 FIX Remove CMS button margin overrides
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/containers/Login.scss
Labels: affects/v4, change/patch

#210 FIX No longer redirects to MFA when no methods are installed on the system
  src/Service/EnforcementManager.php
  tests/php/Service/EnforcementManagerTest.php
Labels: affects/v4, change/patch

#205 NEW Support displaying and setting a default registered method in the member settings fields
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Remove.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/SetDefault.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/FormField/RegisteredMFAMethodListField/tests/MethodListItem-test.js
  client/src/components/FormField/RegisteredMFAMethodListField/tests/RegisteredMFAMethodListField-test.js
  client/src/legacy/RegisteredMFAMethodListFieldEntwine.js
  client/src/state/mfaAdministration/actionTypes.js
  client/src/state/mfaAdministration/actions.js
  client/src/state/mfaAdministration/reducer.js
  client/src/state/mfaAdministration/tests/reducer-test.js
  src/Controller/AdminRegistrationController.php
  src/Extension/MemberExtension.php
  src/FormField/RegisteredMFAMethodListField.php
  src/Model/RegisteredMethod.php
  src/Service/RegisteredMethodManager.php
  tests/php/Controller/AdminRegistrationControllerTest.php
  tests/php/Extension/MemberExtensionTest.php
  tests/php/FormField/RegisteredMFAMethodListFieldTest.php
  tests/php/Service/RegisteredMethodManagerTest.php
Labels: affects/v4, change/minor

#212 FIX Users without CMS access are now able to log in correctly
  src/Authenticator/LoginHandler.php
  src/Service/EnforcementManager.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Service/EnforcementManagerTest.php
Labels: affects/v4, change/patch

#218 FIX Redirect user back when accessing MFA with a stale session
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/BasicMath/Login.js
  src/Authenticator/LoginHandler.php
  src/Controller/AdminRegistrationController.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Authenticator/RegisterHandlerTest.php
Labels: affects/v4, change/patch

#226 Add a basic behat test
  .travis.yml
  behat.yml
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/bundles/bundle-cms.scss
  client/src/components/BackupCodes/Verify.js
  client/src/components/LoadingError.js
  client/src/components/Register/SelectMethod.js
  client/src/components/Verify.js
  client/src/components/tests/Verify-test.js
  client/src/containers/Login.js
  client/src/containers/tests/Login-test.js
  composer.json
  src/Service/EnforcementManager.php
  tests/Behat/Context/LoginContext.php
  tests/Behat/features/mfa-enabled.feature
Labels: affects/v4, change/minor

#227 DOCS Expand Method Creation docs, shift BasicMath components into them
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/boot/registerComponents.js
  client/src/components/BasicMath/Login.js
  client/src/components/BasicMath/Register.js
  docs/en/creating-mfa-method-backend.md
  docs/en/creating-mfa-method-frontend.md
  docs/en/react-components.md
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
  tests/php/Stub/BasicMath/MethodVerifyHandler.php
Labels: affects/v4, type/docs

#233 NEW Update backup codes to use 12 lowercase letters
  docs/en/backup-codes.md
  src/Service/BackupCodeGenerator.php
Labels: affects/v4, change/minor

#231 FIX ensure RegisteredMFAFieldList always has a Member and never "not a Member"
  src/FormField/RegisteredMFAMethodListField.php
  templates/SilverStripe/MFA/FormField/RegisteredMFAMethodListField.ss
  tests/php/FormField/RegisteredMFAMethodListFieldTest.php
  tests/php/FormField/RegisteredMFAMethodListFieldTest.yml
Labels: affects/v4, change/patch

#232 FIX Subsequent admin requests to manage MFA methods no longer reset the CSRF token
  src/RequestHandler/RegistrationHandlerTrait.php
Labels: affects/v4, change/patch

#228 FIX Convert anchors to buttons in recovery code screen and fix broken ref in print button
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/BackupCodes/Register.js
  client/src/components/BackupCodes/Register.scss
  client/src/components/BackupCodes/tests/Register-test.js
Labels: affects/v4, change/patch
