Repository silverstripe/silverstripe-mfa, pull requests merged in 2019-05, with the labels that each got.

#107 NEW Add RegisteredMFAMethodListField component to Member admin
  _config/admin.yml
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/lang/src/en.json
  client/src/bundles/bundle-cms.js
  client/src/bundles/bundle-cms.scss
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.scss
  client/src/components/FormField/RegisteredMFAMethodListField/tests/RegisteredMFAMethodListField-test.js
  client/src/legacy/RegisteredMFAMethodListFieldEntwine.js
  client/src/legacy/index.js
  client/src/legacy/registerComponents.js
  client/src/types/registeredMethod.js
  src/Extension/MemberExtension.php
  src/FormField/RegisteredMFAMethodListField.php
  src/Service/SchemaGenerator.php
  src/State/RegisteredMethodDetails.php
  templates/SilverStripe/MFA/FormField/RegisteredMFAMethodListField.ss
  tests/php/Extension/MemberExtensionTest.php
  tests/php/Extension/MemberExtensionTest.yml
Labels: affects/v4, change/minor

#112 API BackupCodeGenerator::generate() now returns an array of BackupCode instances
  src/BackupCode/RegisterHandler.php
  src/Service/BackupCodeGenerator.php
  src/Service/BackupCodeGeneratorInterface.php
  src/State/BackupCode.php
  tests/php/Service/BackupCodeGeneratorTest.php
Labels: affects/v4, change/major

#109 NEW Moving state for the Register component into redux
  client/dist/js/bundle.js
  client/src/components/Register.js
  client/src/components/Register/Introduction.js
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/tests/Introduction-test.js
  client/src/components/Register/tests/SelectMethod-test.js
  client/src/components/tests/Register-test.js
  client/src/containers/MultiFactorApp.js
  client/src/state/mfaRegister/actionTypes.js
  client/src/state/mfaRegister/actions.js
  client/src/state/mfaRegister/reducer.js
  client/src/state/mfaRegister/tests/reducer-test.js
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#117 API Renaming login to verify
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/index.js
  client/src/boot/registerComponents.js
  client/src/bundles/bundle.scss
  client/src/components/BackupCodes/Verify.js
  client/src/components/BackupCodes/Verify.scss
  client/src/components/BackupCodes/tests/Verify-test.js
  client/src/components/BasicMath/Login.js
  client/src/components/Verify.js
  client/src/components/Verify.scss
  client/src/components/Verify/SelectMethod.js
  client/src/components/Verify/SelectMethod.scss
  client/src/components/tests/Verify-test.js
  client/src/containers/Login.js
  src/Authenticator/LoginHandler.php
  src/BackupCode/Method.php
  src/BackupCode/VerifyHandler.php
  src/Method/Handler/VerifyHandlerInterface.php
  src/Method/MethodInterface.php
  src/Model/RegisteredMethod.php
  src/RequestHandler/VerificationHandlerTrait.php
  src/State/RegisteredMethodDetails.php
  tests/php/Authenticator/VerifyHandlerTest.php
  tests/php/BackupCode/LoginHandlerTest.php
  tests/php/BasicMath/MethodLoginHandlerTest.php
  tests/php/BasicMath/MethodTest.php
  tests/php/State/RegisteredMethodDetailsTest.php
  tests/php/Stub/BasicMath/Method.php
  tests/php/Stub/BasicMath/MethodVerifyHandler.php
Labels: affects/v4, change/major

#122 NEW Adding a method to remove registered methods from a member
  src/Service/RegisteredMethodManager.php
  tests/php/Service/RegisteredMethodManagerTest.php
  tests/php/Service/RegisteredMethodManagerTest.yml
  tests/php/Stub/Null/Method.php
  tests/php/Stub/Null/RegisterHandler.php
  tests/php/Stub/Null/VerifyHandler.php
Labels: affects/v4, change/minor

#126 NEW Moving available methods for Register component into redux state
  client/dist/js/bundle.js
  client/src/components/Register.js
  client/src/containers/Login.js
  client/src/state/mfaRegister/actionTypes.js
  client/src/state/mfaRegister/actions.js
  client/src/state/mfaRegister/reducer.js
  client/src/state/mfaRegister/tests/reducer-test.js
  docs/en/controllers-and-handlers.md
  docs/en/react-components.md
  readme.md
Labels: affects/v4, change/minor

#110 NEW add MFA protection to the reset password flow
  client/dist/js/bundle.js
  client/src/components/BackupCodes/tests/Register-test.js
  client/src/containers/Login.js
  src/Authenticator/ChangePasswordHandler.php
  src/Authenticator/LoginHandler.php
  src/Authenticator/MemberAuthenticator.php
  src/Extension/MemberExtension.php
  src/RequestHandler/BaseHandlerTrait.php
  src/RequestHandler/VerificationHandlerTrait.php
  templates/SilverStripe/MFA/Authenticator/ChangePasswordHandler.ss
  tests/php/Authenticator/ChangePasswordHandlerTest.php
  tests/php/Authenticator/ChangePasswordHandlerTest.yml
Labels: affects/v4, change/minor

#130 FIX Correct invalid reference to register endpoint
  client/dist/js/bundle.js
  client/src/components/BackupCodes/tests/Register-test.js
  client/src/containers/Login.js
Labels: affects/v4, change/patch

#135 FIX Refactor buttons implementations to use same class names and use btn-secondary for non-primary actions
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/bundle.scss
  client/src/components/BackupCodes/Verify.js
  client/src/components/Register/Introduction.js
  client/src/components/Register/Introduction.scss
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/tests/SelectMethod-test.js
  client/src/components/Verify.js
  client/src/components/Verify.scss
  client/src/containers/Login.scss
  client/src/styles/mfa.scss
Labels: affects/v4, change/patch

#141 Add silverstripe/login-forms as direct dependency of silverstripe/mfa
  composer.json
Labels: affects/v4, change/minor

#118 NEW Add MFA to the CMS
  _config/admin.yml
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/boot/cms/index.js
  client/src/boot/cms/registerComponents.js
  client/src/boot/cms/registerReducers.js
  client/src/bundles/bundle-cms.js
  client/src/bundles/bundle-cms.scss
  client/src/bundles/bundle.scss
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/FormField/RegisteredMFAMethodListField/tests/RegisteredMFAMethodListField-test.js
  client/src/components/Register.js
  client/src/components/Register.scss
  client/src/components/Register/Complete.js
  client/src/components/Register/Introduction.js
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/Title.js
  client/src/components/tests/Register-test.js
  client/src/components/tests/__mocks__/lib/Injector.js
  client/src/containers/Login.js
  client/src/containers/Login.scss
  client/src/legacy/RegisteredMFAMethodListFieldEntwine.js
  client/src/legacy/index.js
  client/src/legacy/registerComponents.js
  package.json
  src/Authenticator/ChangePasswordHandler.php
  src/Authenticator/LoginHandler.php
  src/Controller/AdminRegistrationController.php
  src/Extension/RequirementsExtension.php
  src/FormField/RegisteredMFAMethodListField.php
  src/RequestHandler/BaseHandlerTrait.php
  src/Service/MethodRegistry.php
  src/Service/RegisteredMethodManager.php
  src/Store/SessionStore.php
  src/Store/StoreInterface.php
  tests/php/Authenticator/ChangePasswordHandlerTest.php
  tests/php/Authenticator/RegisterHandlerTest.php
  tests/php/Controller/AdminRegistrationControllerTest.php
  tests/php/Controller/AdminRegistrationControllerTest.yml
  yarn.lock
Labels: affects/v4, change/major

#134 NEW email notification for MFA settings update
  src/BackupCode/VerifyHandler.php
  src/Service/Notification.php
  src/Service/RegisteredMethodManager.php
  templates/Email/MFA/Notification_backupcodeused.ss
  templates/Email/MFA/Notification_register.ss
  templates/Email/MFA/Notification_removed.ss
  tests/php/Authenticator/RegisterHandlerTest.yml
  tests/php/BackupCode/VerifyHandlerTest.php
  tests/php/Service/RegisteredMethodManagerTest.php
Labels: affects/v4, change/minor

#127 NEW Add AccountResetUI, with supporting endpoint for sending reset email
  _config/admin.yml
  _config/config.yml
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/bundles/bundle-cms.scss
  client/src/components/BasicMath/Login.js
  client/src/components/FormField/RegisteredMFAMethodListField/AccountResetUI.js
  client/src/components/FormField/RegisteredMFAMethodListField/AccountResetUI.scss
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/FormField/RegisteredMFAMethodListField/tests/AccountResetUI-test.js
  client/src/components/Icons/CircleDash.js
  client/src/components/Icons/CircleTick.js
  client/src/components/LoadingIndicator.js
  client/src/components/LoadingIndicator.scss
  client/src/components/Register.js
  client/src/components/Verify.js
  client/src/components/tests/__mocks__/lib/Config.js
  client/src/containers/Login.js
  client/src/legacy/RegisteredMFAMethodListFieldEntwine.js
  client/src/styles/mfa-variables.scss
  src/BackupCode/VerifyHandler.php
  src/Extension/MemberExtension.php
  src/Extension/MemberResetExtension.php
  src/Extension/SecurityAdminAccountResetExtension.php
  src/FormField/RegisteredMFAMethodListField.php
  src/JSONResponse.php
  src/Service/RegisteredMethodManager.php
  templates/SilverStripe/MFA/Email/AccountReset.ss
  templates/SilverStripe/MFA/Email/Notification_backupcodeused.ss
  templates/SilverStripe/MFA/Email/Notification_register.ss
  templates/SilverStripe/MFA/Email/Notification_removed.ss
  tests/php/Extension/SecurityAdminAccountResetExtensionTest.php
  tests/php/Extension/SecurityAdminAccountResetExtensionTest.yml
  yarn.lock
Labels: affects/v4, change/minor

#146 Fix homepage in package.json, update to webpack-config 1.1.0
  package.json
  yarn.lock
Labels: affects/v4, change/minor
