Repository silverstripe/silverstripe-mfa, pull requests merged in 2019-03, with the labels that each got.

#10 NEW The MFA schema endpoint now returns relevant details
  _config/config.yml
  src/Authenticator/LoginHandler.php
  src/Extension/MemberExtension.php
  src/Method/MethodInterface.php
  src/Model/RegisteredMethod.php
  src/Service/MethodRegistry.php
  src/Store/SessionStore.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Authenticator/LoginHandlerTest.yml
  tests/php/Service/MethodRegistryTest.php
  tests/php/Stub/BasicMath/Method.php
Labels: affects/v4, change/minor

#22 NEW Add MFA enabled, required/optional and grace period settings to SiteConfig
  _config/config.yml
  _config/siteconfig.yml
  client/dist/js/bundle-cms.js
  client/dist/styles/bundle-cms.css
  client/src/bundles/bundle-cms.js
  client/src/bundles/bundle-cms.scss
  client/src/legacy/SiteConfig.js
  client/src/legacy/SiteConfig.scss
  src/Extension/SiteConfigExtension.php
  webpack.config.js
Labels: affects/v4, change/minor

#32 Backend implementation for ability to skip MFA registration/login process
  src/Authenticator/LoginHandler.php
  src/Exception/MemberNotFoundException.php
  src/Extension/MemberExtension.php
  src/Service/EnforcementManager.php
  src/Service/MethodRegistry.php
  src/Service/SchemaGenerator.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Service/EnforcementManagerTest.php
  tests/php/Service/EnforcementManagerTest.yml
  tests/php/Service/SchemaGeneratorTest.php
  tests/php/Service/SchemaGeneratorTest.yml
Labels: affects/v4, change/minor

#33 API Move available and registered method details into encapsulated objects
  _config/state.yml
  src/BackupCode/Method.php
  src/Method/MethodInterface.php
  src/Model/RegisteredMethod.php
  src/Service/SchemaGenerator.php
  src/State/AvailableMethodDetails.php
  src/State/AvailableMethodDetailsInterface.php
  src/State/RegisteredMethodDetails.php
  src/State/RegisteredMethodDetailsInterface.php
  tests/php/Service/SchemaGeneratorTest.php
  tests/php/State/AvailableMethodDetailsTest.php
  tests/php/State/RegisteredMethodDetailsTest.php
  tests/php/Stub/BasicMath/Method.php
Labels: affects/v4, change/minor

#30 API Adding backup code registration/login React components
  .gitignore
  .travis.yml
  _config/backupcodes.yml
  client/dist/js/bundle.js
  client/dist/js/injector.js
  client/dist/styles/bundle.css
  client/lang/.gitkeep
  client/src/boot/index.js
  client/src/boot/registerComponents.js
  client/src/bundles/bundle.scss
  client/src/components/Authenticate.js
  client/src/components/BackupCodes/Login.js
  client/src/components/BackupCodes/Login.scss
  client/src/components/BackupCodes/Register.js
  client/src/components/BackupCodes/Register.scss
  client/src/components/BackupCodes/tests/Login-test.js
  client/src/components/BackupCodes/tests/Register-test.js
  client/src/components/LoadingIndicator.js
  client/src/components/LoadingIndicator.scss
  client/src/components/Login.js
  client/src/components/Register.js
  client/src/components/tests/Login-test.js
  client/src/components/tests/Register-test.js
  client/src/components/tests/__mocks__/lib/Injector.js
  client/src/containers/MultiFactorApp.js
  client/src/styles/mfa-variables.scss
  client/src/types/availableMethod.js
  client/src/types/registeredMethod.js
  package.json
  src/Authenticator/LoginHandler.php
  src/BackupCode/LoginHandler.php
  src/BackupCode/RegisterHandler.php
  src/Method/Handler/LoginHandlerInterface.php
  src/Method/Handler/RegisterHandlerInterface.php
  src/Service/MethodRegistry.php
  src/Service/RegisteredMethodManager.php
  src/State/AvailableMethodDetails.php
  src/State/AvailableMethodDetailsInterface.php
  src/State/RegisteredMethodDetails.php
  src/State/RegisteredMethodDetailsInterface.php
  templates/SilverStripe/MFA/Authenticator/LoginHandler.ss
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/BackupCode/LoginHandlerTest.php
  tests/php/BackupCode/RegisterHandlerTest.php
  tests/php/BackupCode/RegisterHandlerTest.yml
  tests/php/Service/RegisteredMethodManagerTest.php
  tests/php/Service/RegisteredMethodManagerTest.yml
  tests/php/Stub/BasicMath/MethodLoginHandler.php
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
  webpack.config.js
  yarn.lock
Labels: affects/v4, change/major

#48 FIX Pass method interface instead of URL segment in startLogin()
  src/Authenticator/LoginHandler.php
Labels: affects/v4, change/patch

#51 FIX Grace period date no longer has a minimum requirement, since the field itself is optional
  src/Extension/SiteConfigExtension.php
Labels: affects/v4, change/patch

#56 NEW Adding logic to handle a MFA method marked as a backup method & fixing flows
  client/dist/fonts/silverstripe.eot
  client/dist/fonts/silverstripe.svg
  client/dist/fonts/silverstripe.ttf
  client/dist/fonts/silverstripe.woff
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/bundles/bundle.scss
  client/src/components/BasicMath/Login.js
  client/src/components/BasicMath/Register.js
  client/src/components/Login.js
  client/src/components/Register.js
  client/src/components/Register.scss
  client/src/components/Register/Complete.js
  client/src/components/tests/Register-test.js
  client/src/containers/MultiFactorApp.js
  client/src/styles/mfa-variables.scss
  client/src/styles/mfa.scss
  src/Authenticator/LoginHandler.php
  src/Service/EnforcementManager.php
  src/Service/MethodRegistry.php
  src/Service/SchemaGenerator.php
  templates/SilverStripe/MFA/Authenticator/LoginHandler.ss
  tests/php/Stub/BasicMath/MethodLoginHandler.php
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
Labels: affects/v4, change/minor

#57 FIX Fixing phpunit test failures
  src/Authenticator/LoginHandler.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/BasicMath/MethodLoginHandlerTest.php
Labels: affects/v4, change/patch

#59 API Removing setTitle API - Login and Register components render their own titles
  client/dist/js/bundle.js
  client/src/components/Login.js
  client/src/components/Register.js
  client/src/containers/MultiFactorApp.js
Labels: affects/v4, change/minor

#60 Revert license
  LICENSE.md
Labels: affects/v4, type/docs

#62 API Available registration methods are now rendered with their thumbnails and information
  client/dist/images/locked-letter.svg
  client/dist/images/totp.svg
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/bundle.scss
  client/src/components/Register.js
  client/src/components/Register/MethodTile.js
  client/src/components/Register/MethodTile.scss
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/SelectMethod.scss
  client/src/components/Register/tests/MethodTile-test.js
  client/src/components/Register/tests/SelectMethod-test.js
  client/src/components/tests/Register-test.js
  client/src/styles/mfa-variables.scss
  client/src/styles/mfa.scss
  client/src/types/availableMethod.js
  src/BackupCode/Method.php
  src/Method/MethodInterface.php
  src/State/AvailableMethodDetails.php
  src/State/AvailableMethodDetailsInterface.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/State/AvailableMethodDetailsTest.php
  tests/php/Stub/BasicMath/Method.php
Labels: affects/v4, change/minor

#61 NEW Extracting the choose method DOM from Login to its own component
  client/dist/js/bundle.js
  client/src/components/BasicMath/Login.js
  client/src/components/Login.js
  client/src/components/Login/SelectMethod.js
  client/src/components/tests/Login-test.js
  package.json
Labels: affects/v4, change/minor

#64 FIX Update wording on back-up codes
  src/BackupCode/LoginHandler.php
Labels: affects/v4, change/patch
