Repository silverstripe/silverstripe-mfa, pull requests merged in 2019-08, with the labels that each got.

#304 FIX Ensure buttons spacing and restore the confirmation tick for SS3
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/Icons/Check.js
  client/src/components/Register/Complete.js
  client/src/components/Verify.js
  client/src/containers/Login.scss
  client/src/styles/mfa-variables.scss
Labels: affects/v3, change/patch

#307 FIX Remove form-group from backup codes verification screen and compensate for action list padding in content
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/BackupCodes/Register.scss
  client/src/components/BackupCodes/Verify.js
  client/src/components/BackupCodes/Verify.scss
Labels: affects/v4, change/patch

#299 NEW report to show members who have registered an MFA method
  composer.json
  src/Report/EnabledMembers.php
  tests/php/Report/EnabledMembersTest.php
  tests/php/Report/EnabledMembersTest.yml
  tests/php/Stub/Null/Method.php
Labels: affects/v4, change/minor

#310 NEW Add user documentation for MFA, TOTP and WebAuthn modules
  docs/en/userguide/01_User_manual/01_Setting_up_MFA.md
  docs/en/userguide/01_User_manual/02_Using_authenticator_apps.md
  docs/en/userguide/01_User_manual/03_Using_security_keys.md
  docs/en/userguide/01_User_manual/04_Regaining_access.md
  docs/en/userguide/01_User_manual/05_Managing_your_MFA_settings.md
  docs/en/userguide/01_User_manual/index.md
  docs/en/userguide/02_Administrator_manual/01_Configuring_MFA_site_settings.md
  docs/en/userguide/02_Administrator_manual/02_Resetting_accounts.md
  docs/en/userguide/_images/01-01-1-mfa-setup-intro.png
  docs/en/userguide/_images/01-01-2-mfa-select-method.png
  docs/en/userguide/_images/01-01-3-mfa-backup-codes.png
  docs/en/userguide/_images/01-02-1-totp-method-selected.png
  docs/en/userguide/_images/01-02-2-totp-scan.png
  docs/en/userguide/_images/01-02-3-totp-verify.png
  docs/en/userguide/_images/01-02-4-totp-login.png
  docs/en/userguide/_images/01-03-1-security-key-selected.png
  docs/en/userguide/_images/01-03-2-security-key-setup.png
  docs/en/userguide/_images/01-03-3-security-key-progress.png
  docs/en/userguide/_images/01-03-4-security-key-verified.png
  docs/en/userguide/_images/01-03-5-security-key-login.png
  docs/en/userguide/_images/01-03-6-security-key-unavailable.png
  docs/en/userguide/_images/01-04-1-login-prompt.png
  docs/en/userguide/_images/01-04-2-other-options.png
  docs/en/userguide/_images/01-04-3-recovery-code.png
  docs/en/userguide/_images/01-05-1-sudo-mode.png
  docs/en/userguide/_images/01-05-2-add-method.png
  docs/en/userguide/_images/01-05-3-modify-method.png
  docs/en/userguide/_images/01-05-4-reset-recovery-codes.png
  docs/en/userguide/_images/02-01-1-mfa-settings-ui.png
  docs/en/userguide/_images/02-01-2-grace-period.png
  docs/en/userguide/_images/02-02-1-account-reset.png
  docs/en/userguide/_images/02-02-2-account-reset-confirmation.png
  docs/en/userguide/index.md
Labels: affects/v4, type/docs

#311 NEW Add links to userhelp documentation
  src/Authenticator/LoginHandler.php
  src/BackupCode/RegisterHandler.php
Labels: affects/v4, change/minor

#312 Dark Mode support
  client/dist/images/recovery-codes.svg
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/BackupCodes/Register.scss
  client/src/components/FormField/RegisteredMFAMethodListField/AccountResetUI.scss
  client/src/components/Icons/CircleWarning.js
  client/src/components/LoadingIndicator.scss
  client/src/components/Register.scss
  client/src/components/Register/Introduction.scss
  client/src/components/Register/MethodTile.scss
  client/src/components/Verify.scss
  client/src/styles/mfa-variables.scss
  client/src/styles/mfa.scss
Labels: affects/v4, change/minor

#316 API Enabled members report is now performant, no count column/filter, extra method filter options
  src/Report/EnabledMembers.php
  tests/php/Report/EnabledMembersFunctionalTest.php
  tests/php/Report/EnabledMembersTest.php
  tests/php/Report/EnabledMembersTest.yml
Labels: affects/v4, change/major

#319 FIX IE11 inability to download backup codes
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Register.js
Labels: affects/v4, change/patch

#322 FIX Add text class to backup code verification input field so it renders dark in dark mode
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Verify.js
Labels: affects/v4, change/patch

#321 FIX Reduce font size in backup code grid to ensure three columns are displayed
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/BackupCodes/Register.scss
Labels: affects/v3, change/patch

#324 API RegisteredMFAMethodListField now expects a Member ID int as its value
  src/Extension/MemberExtension.php
  src/FormField/RegisteredMFAMethodListField.php
  tests/php/FormField/RegisteredMFAMethodListFieldTest.php
Labels: affects/v4, change/major

#328 FIX setLogger now exists on SecurityAdminExtension
  src/Extension/AccountReset/SecurityAdminExtension.php
  tests/php/Report/EnabledMembersFunctionalTest.php
Labels: affects/v4, change/patch

#330 FIX XHR requests can now resolve the current Member correctly
  src/FormField/RegisteredMFAMethodListField.php
Labels: affects/v4, change/patch

#331 FIX XHR requests can now resolve the current Member correctly
  phpcs.xml.dist
  src/Authenticator/LoginForm.php
  src/BackupCode/RegisterHandler.php
  src/FormField/RegisteredMFAMethodListField.php
  tests/php/Report/EnabledMembersFunctionalTest.php
Labels: affects/v3, change/patch

#332 Add missing allowed prop type
  client/dist/js/bundle-cms.js
  client/src/components/RegisterModal.js
Labels: affects/v4, change/patch

#335 FIX MFA help link now points directly to MFA documentation on the userhelp site
  src/Extension/SiteConfigExtension.php
Labels: affects/v3, change/patch

#334 FIX MFA help link now points directly to MFA documentation on the userhelp site
  src/Extension/SiteConfigExtension.php
Labels: affects/v4, change/patch

#336 FIX Switch to Grid to resolve inconsistent SVG sizing in Intro UI
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/Register/Introduction.js
  client/src/components/Register/Introduction.scss
Labels: affects/v4, change/patch

#338 FIX Reinstate support for three columns of method tiles when multiple of three are installed
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/Register/MethodTile.scss
Labels: affects/v4, change/patch

#341 FIX Images now resolve correctly when project is installed in a subfolder
  src/Service/SchemaGenerator.php
Labels: affects/v3, change/patch

#342 FIX Correct alignment of icons against content in the Introduction UI
  client/dist/images/extra-protection.svg
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/Register/Introduction.scss
Labels: affects/v3, change/patch

#343 FIX Increase spacing between title and content
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/styles/mfa-variables.scss
Labels: affects/v4, change/patch

#345 FIX Use px unit on tick in Complete UI for Firefox compatibility
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/Register/Complete.js
Labels: affects/v3, change/patch

#344 FIX Increase spacing between title and content
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/styles/mfa-variables.scss
  src/Authenticator/LoginForm.php
  src/Extension/ChangePasswordExtension.php
  src/Extension/MemberExtension.php
  src/Store/SessionStore.php
  tests/php/Authenticator/RegisterHandlerTest.php
Labels: affects/v3, change/patch

#348 FIX Update constant visibility and line length for PSR-12 compliance
  src/Authenticator/ChangePasswordHandler.php
  src/Authenticator/LoginHandler.php
  src/BackupCode/RegisterHandler.php
  src/Extension/MemberExtension.php
  src/Store/SessionStore.php
  tests/php/Authenticator/RegisterHandlerTest.php
Labels: affects/v4, change/patch

#347 FIX Enable grace period field on load when MFA is required
  client/dist/js/bundle-cms.js
  client/src/legacy/SiteConfig.js
Labels: affects/v3, change/patch
