Repository silverstripe/silverstripe-mfa, pull requests merged in 2019-04, with the labels that each got.

#74 API Now requires PHP 7.1, add strict types, add encryption adapter with default implementation, add isAvailable and unavailableMessage to AvailableMethodDetailsInterface
  .travis.yml
  _config/encryption.yml
  client/dist/js/bundle.js
  client/src/components/Register/MethodTile.js
  client/src/components/Register/tests/MethodTile-test.js
  client/src/types/availableMethod.js
  composer.json
  readme.md
  src/BackupCode/LoginHandler.php
  src/BackupCode/Method.php
  src/BackupCode/RegisterHandler.php
  src/Exception/AuthenticationFailedException.php
  src/Exception/EncryptionAdapterException.php
  src/Method/Handler/LoginHandlerInterface.php
  src/Method/Handler/RegisterHandlerInterface.php
  src/Method/MethodInterface.php
  src/Service/DefusePHPEncryptionAdapter.php
  src/Service/EncryptionAdapterInterface.php
  src/State/AvailableMethodDetails.php
  src/State/AvailableMethodDetailsInterface.php
  tests/php/Service/PHPEncryptionAdapterTest.php
  tests/php/State/AvailableMethodDetailsTest.php
  tests/php/Stub/BasicMath/Method.php
  tests/php/Stub/BasicMath/MethodLoginHandler.php
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
Labels: affects/v4, change/major

#76 Adjust actions button class names to be more generic for re-use across other components
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/BackupCodes/Register.js
  client/src/components/BackupCodes/tests/Register-test.js
  client/src/components/Register.js
  client/src/components/Register/MethodTile.scss
  client/src/components/Register/SelectMethod.js
  client/src/components/Register/SelectMethod.scss
  client/src/components/Register/tests/SelectMethod-test.js
  client/src/lib/formatCode.js
  client/src/lib/tests/formatCode-test.js
  client/src/styles/mfa.scss
Labels: affects/v4, change/patch

#82 API MethodDetailInterfaces no longer have getters, moved isAvailable() and getUnavailableMessage() to MethodInterface
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Login.js
  client/src/components/Login.js
  src/BackupCode/Method.php
  src/BackupCode/RegisterHandler.php
  src/Method/Handler/RegisterHandlerInterface.php
  src/Method/MethodInterface.php
  src/Model/RegisteredMethod.php
  src/Service/SchemaGenerator.php
  src/State/AvailableMethodDetails.php
  src/State/AvailableMethodDetailsInterface.php
  src/State/RegisteredMethodDetails.php
  src/State/RegisteredMethodDetailsInterface.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Service/SchemaGeneratorTest.php
  tests/php/State/AvailableMethodDetailsTest.php
  tests/php/State/RegisteredMethodDetailsTest.php
  tests/php/Stub/BasicMath/Method.php
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
Labels: affects/v4, change/major

#83 API StoreInterface is now injectable. Removed ::create() in favour of constructor.
  _config/store.yml
  readme.md
  src/Authenticator/LoginHandler.php
  src/Store/SessionStore.php
  src/Store/StoreInterface.php
Labels: affects/v4, change/major

#84 FIX Automatically focus on backup code input field when rendering the component
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Login.js
Labels: affects/v4, change/patch

#87 FIX Register component now handles validation errors, and resets errors between methods
  client/dist/js/bundle.js
  client/src/components/Login.js
  client/src/components/Register.js
  client/src/components/tests/Register-test.js
  src/Authenticator/LoginHandler.php
  tests/php/Authenticator/RegisterHandlerTest.php
Labels: affects/v4, change/major

#91 API Backup code generation has been moved into a BackupCodeGeneratorInterface service
  _config/backupcodes.yml
  src/BackupCode/Method.php
  src/BackupCode/RegisterHandler.php
  src/Service/BackupCodeGenerator.php
  src/Service/BackupCodeGeneratorInterface.php
  tests/php/BackupCode/RegisterHandlerTest.php
  tests/php/Service/BackupCodeGeneratorTest.php
  tests/php/Service/BackupCodeGeneratorTest/MockHashExtension.php
Labels: affects/v4, change/minor

#96 API BackupCodeGenerator::hash() now throws a HashFailedException when the result hash is the same as the plain text input
  src/Exception/HashFailedException.php
  src/Service/BackupCodeGenerator.php
  src/Service/BackupCodeGeneratorInterface.php
  tests/php/Service/BackupCodeGeneratorTest.php
Labels: affects/v4, change/minor

#97 FIX No longer redirect to MFA when MFA is not enabled
  src/Authenticator/LoginHandler.php
  src/Service/EnforcementManager.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Service/EnforcementManagerTest.php
Labels: affects/v4, change/patch

#101 NEW MFA module now has a logger and test state to clear user defined handlers in unit testing
  _config/logging.yml
  readme.md
  src/Authenticator/LoginHandler.php
  src/Dev/State/LoggerTestState.php
Labels: affects/v4, change/minor

#103 NEW Add extension points for audit logging in method registration, login and skip points
  src/Authenticator/LoginHandler.php
  src/Service/RegisteredMethodManager.php
Labels: affects/v4, change/minor

#102 API Moving verification logic to a trait for easier re-usability
  src/Authenticator/LoginHandler.php
  src/Exception/InvalidMethodException.php
  src/RequestHandler/LoginHandlerTrait.php
  src/Service/EnforcementManager.php
  src/Service/MethodRegistry.php
  src/Store/SessionStore.php
  src/Store/StoreInterface.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/Authenticator/RegisterHandlerTest.php
Labels: affects/v4, change/major

#104 NEW Adding a Result class that can be used by Login/Register interfaces for contextual success and failure
  src/Method/Handler/Result.php
Labels: affects/v4, change/minor

#105 API LoginHandler uses Result object instead of booleans, member is locked out via backend API after too many attempts
  src/Authenticator/LoginHandler.php
  src/BackupCode/LoginHandler.php
  src/Method/Handler/LoginHandlerInterface.php
  src/RequestHandler/LoginHandlerTrait.php
  src/State/Result.php
  src/Store/SessionStore.php
  src/Store/StoreInterface.php
  tests/php/Authenticator/LoginHandlerTest.php
  tests/php/BackupCode/LoginHandlerTest.php
  tests/php/BasicMath/MethodLoginHandlerTest.php
  tests/php/State/ResultTest.php
  tests/php/Store/SessionStoreTest.php
  tests/php/Stub/BasicMath/MethodLoginHandler.php
Labels: affects/v4, change/major

#106 API Moving registration logic to a trait for easier re-usability
  src/Authenticator/LoginHandler.php
  src/BackupCode/RegisterHandler.php
  src/Exception/RegistrationFailedException.php
  src/Method/Handler/RegisterHandlerInterface.php
  src/RequestHandler/BaseHandlerTrait.php
  src/RequestHandler/LoginHandlerTrait.php
  src/RequestHandler/RegistrationHandlerTrait.php
  src/State/Result.php
  tests/php/Authenticator/RegisterHandlerTest.php
  tests/php/BackupCode/RegisterHandlerTest.php
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
Labels: affects/v4, change/major

#108 Add configurable copyFeedbackDuration, speed up tests
  client/dist/js/bundle.js
  client/src/components/BackupCodes/Register.js
  client/src/components/BackupCodes/tests/Register-test.js
Labels: affects/v4, change/minor
