Repository silverstripe/silverstripe-mfa, pull requests merged in 2019-07, with the labels that each got.

#242 API alter user help link default translations
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/components/BackupCodes/Register.js
  client/src/components/BackupCodes/Verify.js
  client/src/components/BackupCodes/tests/Register-test.js
  client/src/components/Register/Introduction.js
  client/src/components/Register/MethodTile.js
  client/src/components/Register/tests/Introduction-test.js
  lang/en.yml
  phpcs.xml.dist
  src/BackupCode/RegisterHandler.php
  src/Controller/AdminRegistrationController.php
  src/FormField/RegisteredMFAMethodListField.php
  src/Method/Handler/RegisterHandlerInterface.php
  src/Service/SchemaGenerator.php
  src/State/AvailableMethodDetails.php
  tests/php/Stub/BasicMath/MethodRegisterHandler.php
  tests/php/Stub/Null/RegisterHandler.php
Labels: affects/v4, change/major

#243 FIX SessionStore no longer persists the member's password during MFA login
  docs/en/datastores.md
  src/Authenticator/LoginHandler.php
Labels: affects/v4, change/patch

#265 FIX Show jQuery datepicker on MFA grace period selection field
  src/Extension/SiteConfigExtension.php
Labels: affects/v3, change/patch

#269 Adjust font sizing and spacing across the Intro and Method Select UIs
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/Register/Introduction.scss
  client/src/components/Register/MethodTile.scss
  client/src/styles/mfa-variables.scss
  client/src/styles/mfa.scss
Labels: affects/v4, change/patch

#270 FIX Ignore project defined password strength rules in MFA unit tests
  tests/php/Extension/AccountReset/SecurityExtensionTest.php
Labels: affects/v4, change/patch

#272 FIX incorrect versions in the readme
  readme.md
Labels: affects/v3, type/docs

#277 FIX Defer member access for performance and cases where DB is not available on session start
  src/Store/SessionStore.php
  tests/php/Store/SessionStoreTest.php
Labels: affects/v4, change/patch

#280 Extract fetch calls, add explicit credentials config for Edge 14-17 support
  client/dist/js/bundle-cms.js
  client/dist/js/bundle.js
  client/src/components/FormField/RegisteredMFAMethodListField/AccountResetUI.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Remove.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/SetDefault.js
  client/src/components/Register.js
  client/src/components/Verify.js
  client/src/components/tests/Register-test.js
  client/src/components/tests/Verify-test.js
  client/src/containers/Login.js
  client/src/lib/api.js
  client/src/lib/tests/api-test.js
Labels: affects/v4, change/minor

#279 NEW Add a prop to disallow registration screens from showing in the modal
  client/dist/js/bundle-cms.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Reset.js
  client/src/components/FormField/RegisteredMFAMethodListField/RegisteredMFAMethodListField.js
  client/src/components/RegisterModal.js
Labels: affects/v4, change/minor

#285 Prevent methods from being registered more than once
  readme.md
  src/Service/MethodRegistry.php
  tests/php/Service/MethodRegistryTest.php
  tests/php/Stub/BasicMath/Method.php
  tests/php/Stub/DuplicatedBasicMath/Method.php
Labels: affects/v4, change/minor

#286 DOCS Add hypothetical guide to integrating MFA into another authenticator e.g. LDAP
  _config/config.yml
  docs/en/other-authenticators.md
  readme.md
Labels: affects/v3, change/patch

#284 DOCS Add security documentation incl. login attempts, fix readme links to "create method" files
  docs/en/encryption.md
  docs/en/security.md
  readme.md
Labels: affects/v4, type/docs

#283 API Remove LoggerTestState for SS3, update docs, fix broken class names and optimise imports
  _config/logging.yml
  docs/en/debugging.md
  src/Authenticator/LoginForm.php
  src/Authenticator/MemberAuthenticator.php
  src/Controller/AdminRegistrationController.php
  src/Dev/State/LoggerTestState.php
  src/Extension/AccountReset/MFAResetExtension.php
  src/Extension/AccountReset/SecurityAdminExtension.php
  src/Extension/AccountReset/SecurityExtension.php
  src/Extension/MemberExtension.php
  src/Extension/SiteConfigExtension.php
  src/RequestHandler/BaseHandlerTrait.php
  src/RequestHandler/RegistrationHandlerTrait.php
  src/Service/BackupCodeGenerator.php
  src/Service/MethodRegistry.php
  src/Service/RegisteredMethodManager.php
  src/Service/SchemaGenerator.php
  src/State/BackupCode.php
  src/State/Result.php
Labels: affects/v4, change/patch

#282 Remove lang files from SS3 version
  lang/_manifest_exclude
  lang/en.yml
Labels: affects/v3, change/patch

#281 FIX Disable hover styles for unsupported method options in registation
  client/dist/styles/bundle-cms.css
  client/dist/styles/bundle.css
  client/src/components/Register/MethodTile.scss
Labels: affects/v4, change/patch

#289 FIX Default methods are assumed on first method and removal of last method
  client/dist/js/bundle-cms.js
  client/src/components/FormField/RegisteredMFAMethodListField/MethodListItem/Remove.js
  client/src/components/RegisterModal.js
Labels: affects/v4, change/patch

#287 DOCS Add hypothetical guide to integrating MFA into another authenticator e.g. LDAP
  _config/config.yml
  docs/en/other-authenticators.md
  readme.md
Labels: affects/v4, type/docs

#293 FIX Prevent early backup code generation during registration process
  src/BackupCode/RegisterHandler.php
  tests/php/BackupCode/RegisterHandlerTest.php
Labels: affects/v3, change/patch

#291 API RegisteredMFAMethodListField now expects a Member ID int as its value
  src/Extension/MemberExtension.php
  src/FormField/RegisteredMFAMethodListField.php
  tests/php/FormField/RegisteredMFAMethodListFieldTest.php
Labels: affects/v3, change/major
